### ISSUE TITLE
have some UI bugs in macOS 10.14.6 's Dark Mode

### ISSUE THREAD

**Issue by TristenChenTao** [ian4hu/Clipy#13]
have some UI bugs in macOS 10.14.6 's Dark Mode

like this
![image](https://user-images.githubusercontent.com/2186895/63004678-89add000-bead-11e9-9835-2636f92d5a69.png)

![image](https://user-images.githubusercontent.com/2186895/63004802-cc6fa800-bead-11e9-8c96-5bb40605f62b.png)

![image](https://user-images.githubusercontent.com/2186895/63005002-4011b500-beae-11e9-8ea3-1e02bde3ac80.png)

**Comment by ian4hu** [comment]
Fixed by #17
