### ISSUE TITLE
doesn't remove anything else for a plain text paste.

### ISSUE THREAD

**Issue by ian4hu** [ian4hu/Clipy#16]
https://github.com/Clipy/Clipy/issues/319#issuecomment-521322293
 @JML54 
> The new build has introduced another problem. Right-click on a snippet does not paste plain text anymore. It reduces the font size to 8.5 regardless of the original font size and doesn't remove anything else for a plain text paste.

**Comment by ian4hu** [comment]
@JML54 could you give me more details about the new bug?

**Comment by JML54** [comment]
Before the update, a right click in Clipy would paste plain unformatted text.  After the update, every right-click would paste 8.5 point text into an MS Word document (and that was not the default font in the document), no matter the font styles of the original text chosen for the clipboard.  No changes in Clipy preferences.  Same behavior in Apple Mail.  Clipy was also keeping two copies of the selected text in the clipboard.

**Comment by ian4hu** [comment]
> After

I could not found the difference between left-click and right-click from the source code of Clipy before the update. but paste as plain text by right-click could be a feature.
What I am sure is that the update actual import changes for duplicate item in the menu.
