### ISSUE TITLE
Sort history by "Date created": latest copied should be at the top

### ISSUE THREAD

**Issue by afeblot** [ian4hu/Clipy#30]
Hi,
In version 1.2.8, when the sort order is set to "Date created", we get the latest copied at the bottom. It would make more sense to have it at the top, as recently copied items are more likely to be pasted than older ones.

Could you either 
- reverse the sort,
- or add a 3rd sort choice: "Reversed Date Created",
- or add a distinct new option to chose the sort direction?

Thanks

**Comment by afeblot** [comment]
Any comment? agree? disagree?

**Comment by ian4hu** [comment]
sort by `Date created` is ascending or descending?

**Comment by afeblot** [comment]
I'm not sure how to understand ascending or descending in this context, but currently, with `Date created`, the most recent items get displayed at the bottom of the list. I'd be happy to have them instead at the top of the list.

**Comment by ian4hu** [comment]
> I'm not sure how to understand ascending or descending in this context, but currently, with `Date created`, the most recent items get displayed at the bottom of the list. I'd be happy to have them instead at the top of the list.
> 
> Somehow related issue: if I set
> 
> * `Max clipboard history size` to 30 items
> * `Number of items place inline` to 30 items too (because I don't want any items in a folder)
>   Then, after the first 30 copied items in the list, no further copied items is added to the list, whereas they should rotate, I suppose (oldest items should be discarded to allow new items to be added to the list).

The history is already rotated.

**Comment by afeblot** [comment]
@ian4hu , thanks for the fix of #35 through #36. However this issue (#30) is **not** fixed: This issue is asking for a way to reverse the sort order when using sort by "Date Created". Quoting my initial request:

> Could you either
>     * reverse the sort,
>     * or add a 3rd sort choice: "Reversed Date Created",
>     * or add a distinct new option to chose the sort direction?

Thanks

**Comment by ian4hu** [comment]
IMO, Sort by `Date Created` is a total different to `Last Used`, and it will make history sort by create time with natural order (the last created will on the bottom). So if there is a sort order like `Reversed Date Created`, what the different compare with `last used`?

**Comment by ian4hu** [comment]
Could you explain your situation about the Reversed sort? @afeblot

**Comment by afeblot** [comment]
Ah, you're right. I think your change in #36 also fixed the behavior of the "Last used" ordering, which is now exactly as what I expect, whereas it really was not initially.
Thanks and sorry. 👍
