### ISSUE TITLE
Request: Selective History Deletion

### ISSUE THREAD

**Issue by whitverj** [ian4hu/Clipy#33]
Clearing the history is currently all-or-nothing.  Sometimes you might copy/paste sensitive information that you don't want retained, but you want to maintain other items in your history.  Being able to selectively remove items from Clipy's history would be a wonderful addition to the app.

Thank you for taking over this project; I'm very glad to see it's still alive (just upgraded from ClipMenu 0.4.3).

**Comment by ian4hu** [comment]
@whitverj 
Good suggestion. I am not sure that the NSMenu support multi-selection or not. Do you have any research on it?

**Comment by tessus** [comment]
@whitverj as a `delete-one-item` workaround you can set the following in Beta Preferences:

<img width="392" alt="image" src="https://user-images.githubusercontent.com/223439/68075560-95f44b80-fd7f-11e9-8539-e063c76f4a2c.png">

And then just control click on an entry and it's gone.

**Comment by ian4hu** [comment]
> @whitverj as a `delete-one-item` workaround you can set the following in Beta Preferences:
> 
> <img alt="image" width="392" src="https://user-images.githubusercontent.com/223439/68075560-95f44b80-fd7f-11e9-8539-e063c76f4a2c.png">
> 
> And then just control click on an entry and it's gone.

That could delete item one by one.

@whitverj  Do you mean the `batch deletion` feature?

**Comment by whitverj** [comment]
I think the preference listed above would probably do the job - as long as one doesn't get too many items in the history before remembering to clear them out.
