### ISSUE TITLE
Items not rotated after the max number of displayed items has been reached

### ISSUE THREAD

**Issue by afeblot** [ian4hu/Clipy#35]
On MacOS 10.14.6, using Clipy 1.2.9 beta 11:

If `Max clipboard history size` is set to the same value as `Number of items place inline` (lets's call it `x`), there is a history rotation issue after recording the first `x` items.

Please download the screencast showing the issue here (will only be hosted for 100 days): http://s000.tinyupload.com/?file_id=66911547351521227948

The history is sometimes rotated way later (like 15 minutes later). If the rotation is triggered by a specific action of mine, I've not been able to find out which one it is.

**Comment by ian4hu** [comment]
Ok I see. that is same as #30

**Comment by ian4hu** [comment]
You could temporally  `fix` it by set  order history with  `last used`

**Comment by ian4hu** [comment]
![image](https://user-images.githubusercontent.com/7564574/68083113-fd81c800-fe5f-11e9-91e1-dbe7aa6c35bd.png)

**Comment by ian4hu** [comment]
Fixed by #36
