### ISSUE TITLE
"Clear History" disabled in 1.2.9 beta 12

### ISSUE THREAD

**Issue by afeblot** [ian4hu/Clipy#37]
The "Clear History" command from the menu is disabled in 1.2.9 beta 12. It was fine in 1.2.9 beta 11.
![Clipy 2019-11-07 23-53-55](https://user-images.githubusercontent.com/12073123/68434707-ec1b2180-01b9-11ea-8435-6fff1367942a.png)

**Comment by ian4hu** [comment]
My mistake, it will be fixed soon.

**Comment by iambudi** [comment]
Hi, what release that fix this issue? Thanks

**Comment by rmorrin** [comment]
Can you please publish a new release that includes this fix? Or provide instructions on building manually. Thanks.

**Comment by ian4hu** [comment]
released.
