### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by afeblot** [ian4hu/Clipy#38]
With all Clipy versions I have tried, up to 1.2.9 beta 12, images are not displayed in the menu, despite the following settings:
![Clipy - Setting 2019-11-08 00-16-12](https://user-images.githubusercontent.com/12073123/68436010-14f0e600-01bd-11ea-8e3b-0fabe0d9f0b6.png)
![Monosnap 2019-11-08 00-19-02](https://user-images.githubusercontent.com/12073123/68436170-892b8980-01bd-11ea-992c-fc0e94d1aeeb.png)

(images are however properly copied to Clippy and pasted from Clippy)

**Comment by ian4hu** [comment]
@afeblot  you should also check the `Display icons in menu items`
![image](https://user-images.githubusercontent.com/7564574/68524027-2a205e80-02fc-11ea-8b84-0b2d5320cce1.png)

**Comment by afeblot** [comment]
Ah, thanks, I get it now.

Do you think you'd be able (and willing) to display the images where you currently just print "(image)", instead of having them at the icon position?

Rationale: 
* The image is the actual copied content, so it would be consistent (and nicer) to have it located  at the same position as copied texts.
* That would allow to have images displayed even if we hide icons (most of the time, icons don't bring so much value, they're almost identical and just bloat the window).
