### ISSUE TITLE
Screenshots missing from Clipy history

### ISSUE THREAD

**Issue by puranzhang** [ian4hu/Clipy#40]
Hi there, I'm currently on **Catalina 10.1.5.1** and **Clipy 1.2.9 beta12**. I noticed that I'm unable to retrieve screenshots from Clipy with all these settings checked:

<img width="592" alt="Screen Shot 2019-11-11 at 09 50 43" src="https://user-images.githubusercontent.com/9508376/68608834-bbacdf00-0468-11ea-922c-a3fc0cf87844.png">
<img width="592" alt="Screen Shot 2019-11-11 at 09 44 49" src="https://user-images.githubusercontent.com/9508376/68608867-cf584580-0468-11ea-8820-5ecdf2a39d0c.png">

Is this a known issue? Thanks for help!

**Comment by ian4hu** [comment]
Have you tried the latest release version? I am not sure where is the problem. In my device the latest release version is work perfect.

**Comment by puranzhang** [comment]
The latest version being _1.2.9.beta12_ right? Yeah I'm using that one, and can't get the screenshot. I even tried rolling back to 1.2.6, but couldn't get screenshot work neither.

**Comment by ian4hu** [comment]
You can disable `Save screenshots in history` and the re-enable it and try again.

**Comment by ahmaduhhs** [comment]
uncheck the "Save screenshots in history" and restart the app it works well in 10.15 w/latest Clipy app.

**Comment by rjamorim** [comment]
The suggestion above worked for me
(uncheck "Save screenshots in history" in the Beta pane, restart Clipy, check again "Save screenshots in history", restart again)

Running on 10.15.7
