### ISSUE TITLE
Input Command + V after item selection does not work with Russian layout

### ISSUE THREAD

**Issue by Defman21** [ian4hu/Clipy#44]
I'm using Dvorak and Russian layouts. If I use Dvorak, then selecting an item from the history pastes it. But If I use Russian layout, it doesn't.

**Comment by ian4hu** [comment]
Would you mind describing your problem with more details information?

Is the automatic paste action is not work with Russian layout after you select a menu item?

**Comment by Defman21** [comment]
Yes. It works only with English layouts (ABC, US, Dvorak).

**Comment by ian4hu** [comment]
@Defman21 Could you try the latest release?

**Comment by Defman21** [comment]
Oh, I've moved to another clipboard app but I'll try it anyways.

**Comment by Defman21** [comment]
Seems to be working for the Russian layout, but broken in Dvorak-Qwerty (DQ). I've filed a bug #67
