### ISSUE TITLE
Cannot open / restore Clipy MenuBar menu or Settings window.

### ISSUE THREAD

**Issue by theMajc** [ian4hu/Clipy#47]
After configuring Clipy to hide Dock and MenuBar icon, I cannot find a way to restore it. And thus cannot open Clipy's main menu.

This issue has been mentioned in https://github.com/Clipy/Clipy/issues/386, but clearing all Clipy related files described in https://github.com/ian4hu/Clipy/issues/32 did not help. 

Actions taken:
Removed files found in `find ~/Library | grep -i clipy` and `find /Library | grep -i clipy`. 
Also removed all _ClipMenu_ related files.
Removed `/Applications/Clipy.app` and "reinstalled".

**Comment by theMajc** [comment]
After several content clear and reinstall, it did not work, but I guess at some point, I restarted my Mac, and Clipy reset itself, started to show the icon, as well as a "Preference" item in the main menu.

**Comment by aroop** [comment]
I had the same issue. It worked for me after removing the clipy related files from ~/Library.

Thanks @theMajc
