### ISSUE TITLE
[Feature Request] Please add the option for native blue MacOS folder icons in the clip menu

### ISSUE THREAD

**Issue by lothar-cell** [ian4hu/Clipy#50]
As it was in the original clip menu, just looks more native (the original icon was also cooler).

**Comment by lothar-cell** [comment]
![screenshot1](https://user-images.githubusercontent.com/2356354/78449699-b7cd6380-767a-11ea-9a7e-1022bfb987c9.png)

**Comment by ian4hu** [comment]
I will try to git the native folder icon back.

**Comment by ian4hu** [comment]
released by #52
