### ISSUE TITLE
Publish a release with latest fixes

### ISSUE THREAD

**Issue by rmorrin** [ian4hu/Clipy#51]
Hi there,

Would it be possible to publish a new release with the latest fixes? In particular, I am interested in
https://github.com/ian4hu/Clipy/issues/37 which doesn't seem to be included in the last (1.2.9.beta12) release.

I did attempt to build the project myself, but have newer versions of XCode and Swift installed than those mentioned in the readme and received a number of errors.

Thank you!

**Comment by ian4hu** [comment]
It will be released soon.

**Comment by ian4hu** [comment]
Fixed by #52
