### ISSUE TITLE
Number list displays after pics

### ISSUE THREAD

**Issue by chenxiccc** [ian4hu/Clipy#6]

**Comment by chenxiccc** [comment]
<img width="344" alt="Xnip2019-08-09_12-33-12" src="https://user-images.githubusercontent.com/1096853/62754438-6694b200-baa2-11e9-8b96-4f87c0528f89.png">

**Comment by ian4hu** [comment]
caused by  the tiff content us used as icon for menu item. Actually there should be a type hint like `(Image)` after the number index.
