### ISSUE TITLE
Monterey M1 - Can't get past "Clipy" would like to control this computer

### ISSUE THREAD

**Issue by dk253** [ian4hu/Clipy#64]
Greetings,  I know this was a closed issue, but I am stuck.  New computer.  I keep getting the security dialog blocking execution.  I have been through the process, I have deleted the app and re-added it in the accessibility security system pref dialog.  I have cleaned out all of the ~/Library files that pertain to Clipy and tried reinstalling.  No love!

Any suggestions?

![Screen Shot 2021-11-23 at 9 11 05 AM](https://user-images.githubusercontent.com/6131657/143072773-1f2d4795-3824-440f-ac18-6e2a74a169d7.png)
s

![Screen Shot 2021-11-23 at 9 18 29 AM](https://user-images.githubusercontent.com/6131657/143072862-755971c0-083c-4137-8daf-b59af1b072a3.png)
?

**Comment by dk253** [comment]
OK...  a little more information.  I backtracked to beta 12 and at least it started.  It still came up with the dialog.  Then I deleted it from the sec & priv accessibility perms and dragged the new one back in.  It seems to be working.

**Comment by borekb** [comment]
I can confirm that I wasn't able to run Clipy on an M1 Mac, didn't try beta 12 but the latest release doesn't work.

**Comment by dk253** [comment]
Beta 12 has been working fine even through a few reboots.  Wonder what I'm missing through Beta 18.  :-)

**Comment by borekb** [comment]
Confirming that [1.2.11](https://github.com/ian4hu/Clipy/releases/tag/1.2.11) works 🎉.

**Comment by dk253** [comment]
Me too!  Awesome!  Thanks!!
