### ISSUE TITLE
Clipy keep asking for accessibility permission even it's already enabled

### ISSUE THREAD

**Issue by Bossa573** [ian4hu/Clipy#66]
![image](https://user-images.githubusercontent.com/1013526/144555838-59c90e89-3c29-4438-b98c-7a113d70bbe5.png)

I don't know if it's related to I have ever tried to open the version of github.com/clipy/clipy and messed up macOS's system permission history.
Now no matter how I open this version (github.com/ian4hu/Clipy), 
the app keep asking for allowing accessibility permission,
I have tried to uncheck and check the permission,
delete the entry and open the app again to trigger the entry back,
delete the entry and adding the entry manually,
still cannot grant the app's permission properly

Or is that possible because same app identifier used between this version and the OG one?

Environment:
macOS 12.0.1
2021 MBP M1

Tried other clipboard managers such as copyQ or Maccy, can grant the permission normally.

**Comment by Bossa573** [comment]
![permission](https://user-images.githubusercontent.com/1013526/144557582-dbdcf57a-a4bd-48f8-9a56-0cad1dba20c6.gif)

added a gif video for better illustration to the issue

**Comment by boer0327** [comment]
since updated to the latest version, I got the same issue. there are should be something wrong. I have tried to remove and re-aad on accessibility multi times, but it still got the same result.

Environment:
macOS 12.0.1
2022 MBP M1 Pro
![image](https://user-images.githubusercontent.com/1627892/144572676-2a8986d8-ec48-413d-a35e-b84e8c886a8c.png)

**Comment by Bossa573** [comment]
btw, OG version (github.com/clipy/clipy) permission works normally (but no longer able to grab clipboard image buffer)

**Comment by ian4hu** [comment]
After I remove the accessibility item for Clipy, this problem occur. It seems the new macOS version have done some restriction to unsigned apps. I am working at this.

**Comment by ian4hu** [comment]
@Bossa573 Could you please try the latest release, It build with codesign feature. And I tested it on my macbook, it works fine.

**Comment by Bossa573** [comment]
@ian4hu works perfectly for both text and image, thank you very much!
